"""integrity fields

Revision ID: 08f2bc5197e7
Revises: 311480ed75d1
Create Date: 2026-09-07 16:18:17.340501
"""
from alembic import op
import sqlalchemy as sa


revision = '08f2bc5197e7'
down_revision = '311480ed75d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('integrity_error', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('integrity_error')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###
