"""meta timestamps

Revision ID: 10d684024d8b
Revises: 49decec65e02
Create Date: 2026-09-08 14:01:48.928989
"""
from alembic import op
import sqlalchemy as sa


revision = '10d684024d8b'
down_revision = '49decec65e02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('meta_updated_at')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('meta_updated_at')

    # ### end Alembic commands ###
