"""keep_source

Revision ID: 1df5b37f2c5a
Revises: 08f2bc5197e7
Create Date: 2026-09-07 16:23:58.026721
"""
from alembic import op
import sqlalchemy as sa


revision = '1df5b37f2c5a'
down_revision = '08f2bc5197e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keep_source', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('keep_source')

    # ### end Alembic commands ###
