"""upload rel_path

Revision ID: 29d28b29231a
Revises: 010c4bb8997c
Create Date: 2026-09-07 14:27:33.760128
"""
from alembic import op
import sqlalchemy as sa


revision = '29d28b29231a'
down_revision = '010c4bb8997c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rel_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('rel_path')

    # ### end Alembic commands ###
