"""streaming bundles

Revision ID: 311480ed75d1
Revises: 734608a7a2ca
Create Date: 2026-09-07 16:13:27.842430
"""
from alembic import op
import sqlalchemy as sa


revision = '311480ed75d1'
down_revision = '734608a7a2ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('manifest', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('written', sa.BigInteger(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('completed_members', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_bundles_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key('fk_bundles_file_id', 'files', ['file_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crc32', sa.BigInteger(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('crc32')
        batch_op.drop_column('member_index')

    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bundles_file_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bundles_file_id'))
        batch_op.drop_column('completed_members')
        batch_op.drop_column('written')
        batch_op.drop_column('manifest')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
