"""shared workspace

Revision ID: 49decec65e02
Revises: 63d75a1def50
Create Date: 2026-09-08 13:56:48.609408
"""
from alembic import op
import sqlalchemy as sa


revision = '49decec65e02'
down_revision = '63d75a1def50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')

    # ### end Alembic commands ###
