"""content encryption

Revision ID: 63d75a1def50
Revises: b8cf143f1a13
Create Date: 2026-09-08 13:25:11.834724
"""
from alembic import op
import sqlalchemy as sa


revision = '63d75a1def50'
down_revision = 'b8cf143f1a13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_salt', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('enc_size', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('key_id', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('key_id')
        batch_op.drop_column('encrypted')

    with op.batch_alter_table('file_parts', schema=None) as batch_op:
        batch_op.drop_column('enc_size')
        batch_op.drop_column('enc_salt')

    # ### end Alembic commands ###
