"""streaming parts

Revision ID: 734608a7a2ca
Revises: 29d28b29231a
Create Date: 2026-09-07 16:02:36.620951
"""
from alembic import op
import sqlalchemy as sa


revision = '734608a7a2ca'
down_revision = '29d28b29231a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received', sa.BigInteger(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('staging_path', sa.String(length=512), nullable=True))

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_uploads_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key('fk_uploads_file_id', 'files', ['file_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_uploads_file_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_uploads_file_id'))
        batch_op.drop_column('file_id')

    with op.batch_alter_table('file_parts', schema=None) as batch_op:
        batch_op.drop_column('staging_path')
        batch_op.drop_column('received')

    # ### end Alembic commands ###
