"""chunk map

Revision ID: 8a3b4d29d8d8
Revises: 1df5b37f2c5a
Create Date: 2026-09-07 16:58:18.070118
"""
from alembic import op
import sqlalchemy as sa


revision = '8a3b4d29d8d8'
down_revision = '1df5b37f2c5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_map', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('prefix_chunks', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('prefix_chunks')
        batch_op.drop_column('chunk_map')

    # ### end Alembic commands ###
