"""totp

Revision ID: e8e3fcbe3c7e
Revises: 8a3b4d29d8d8
Create Date: 2026-09-08 12:47:11.038768
"""
from alembic import op
import sqlalchemy as sa


revision = 'e8e3fcbe3c7e'
down_revision = '8a3b4d29d8d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_last_counter', sa.BigInteger(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recovery_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recovery_codes')
        batch_op.drop_column('totp_last_counter')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
